[package]
name = "line_prefixer"
version = "0.1.0"
edition = "2024"
authors = ["Dima P <dimapm@pm.me>"]
license = "MIT"
description = "Crate to add prefix to the lines when it used with other writers"
readme = "README.md"
documentation = "https://docs.rs/line_prefixer"
homepage = "https://github.com/di-rs/line_prefixer"
repository = "https://github.com/di-rs/line_prefixer"
keywords = ["line_prefixer", "prefix", "writer", "line_prefixer"]
exclude = [".github/*"]

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
